source "https://api.berkshelf.com"

cookbook 'build-essential'
cookbook 'git'
cookbook 'memcached'
cookbook 'nodejs'
#cookbook 'database'
cookbook 'xml'
cookbook 'libev'
cookbook 'ruby_build'
cookbook 'openssl'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'nginx'
cookbook 'imagemagick'
cookbook 'simple_iptables', git:"git://github.com/dcrosta/cookbook-simple-iptables.git"
cookbook 'hostsfile', '~> 2.4.5'
